/* Machine-readable behaviour for every tech and module, keyed by the name in
   tech-presets.js / mod-presets.js. The presets stay the single source of DISPLAY text;
   this file is the single source of BEHAVIOUR. validate-effects.js checks the two agree.

   Shape:
     onPlay:   [op, ...]                 resolved when the card is played
     activate: { cost:[op], effect:[op] } an On Activate ability; cost is paid first
     passive:  [{ trigger, effect:[op], optional }]
     placement: for modules — where they may be built
   Any op field may be the string 'choose', which raises a prompt. */
var CARD_EFFECTS = {

/* ============================ TECHS ============================ */
tech: {

/* --- module creators: play, spawn, trash --- */
'Cannon Unit':            { onPlay:[{op:'createModule',module:'Cannon'},{op:'trashSelf'}] },
'P.D. Unit':              { onPlay:[{op:'createModule',module:'P.D.'},{op:'trashSelf'}] },
'Armor Unit':             { onPlay:[{op:'createModule',module:'Armor'},{op:'trashSelf'}] },
'DEW Unit':               { onPlay:[{op:'createModule',module:'Directed Laser Beam'},{op:'trashSelf'}] },
'Graviton Unit':          { onPlay:[{op:'createModule',module:'Graviton Engine'},{op:'trashSelf'}] },
'Thrust Unit':            { onPlay:[{op:'createModule',module:'Thrust Engine'},{op:'trashSelf'}] },
'Comms Unit':             { onPlay:[{op:'createModule',module:'Comms Unit'},{op:'trashSelf'}] },
'Shield Unit':            { onPlay:[{op:'createModule',module:'Shield Connector'},{op:'trashSelf'}] },
'SPEAR Unit':             { onPlay:[{op:'createModule',module:'SPEAR Connector'},{op:'trashSelf'}] },
'Repulsor Unit':          { onPlay:[{op:'createModule',module:'Repulsor Unit'}] },
'Quantum Disrupter Unit': { onPlay:[{op:'createModule',module:'Quantum Disrupter'}] },
'Citadel':                { onPlay:[{op:'gainHull',n:5,mayExceed:true,target:'core'},
                                    {op:'createModule',module:'Citadel'},{op:'trashSelf'}] },

/* --- charge banks that spawn deployables / modules --- */
'Torpedo Launcher':       { onPlay:[{op:'addCharge',target:'self',n:4}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'createDeployable',deployable:'Ion Torpedo'}] } },
'Fusion Mine Launcher':   { onPlay:[{op:'addCharge',target:'self',n:2}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'createDeployable',deployable:'Fusion Mine'}] } },
'TAT Launcher':           { onPlay:[{op:'addCharge',target:'self',n:1}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'createDeployable',deployable:'TAT Guided'}] } },
'Decoy Launcher':         { activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'createDeployable',deployable:'Decoy Deployable'}] } },
'Decoy Builder':          { onPlay:[{op:'addCharge',target:'self',n:4}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'createModule',module:'Decoy Module'}] } },

/* --- direct-fire weapons --- */
'Rocket Array':           { onPlay:[{op:'addCharge',target:'self',n:1},{op:'exhaustSelf'}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'attack',range:9,from:'any',attacks:8,dmg:1}] } },
'Mag Bomb Array':         { onPlay:[{op:'addCharge',target:'self',n:2},{op:'exhaustSelf'}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'attack',range:4,from:'offenseModule',attacks:3,dmg:1,
                                                dmgType:'kinetic',chainOnHullHit:true}] } },
'Asteroid Lance':         { activate:{ cost:[{op:'exhaustSelf'},{op:'consumeAsteroid',within:'sensors'}],
                                       effect:[{op:'attack',range:'sensors',from:'any',attacks:1,dmg:3,
                                                check:'Sensors',dmgType:'kinetic'}] } },
'Burning Wave':           { activate:{ mode:'choice', options:[
                              { label:'Add 3 Heat', cost:[{op:'exhaustSelf'}],
                                effect:[{op:'addHeat',target:'self',n:3}] },
                              { label:'Fire', cost:[{op:'exhaustSelf'},{op:'spendAllHeat'}],
                                effect:[{op:'attack',range:1,from:'any',attacks:'heatSpent',dmg:1,
                                         dmgType:'kinetic'}] } ] } },
'Target Locking':         { passive:[{ trigger:'onDealDamage',
                                       effect:[{op:'addCharge',target:'self',n:1,resetOnNewTarget:true}] }],
                            activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'attack',range:'sensors',from:'any',
                                                attacks:'charges',dmg:1,target:'locked'}] } },
'Fire Shield':            { passive:[{ trigger:'onShieldDamaged',
                                       effect:[{op:'addHeat',target:'self',n:1}] }],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendHeat',n:'upTo4'}],
                                       effect:[{op:'attack',range:'sensors',from:'any',aoe:'allObjects',
                                                attacks:'heatSpent',dmg:1,dmgType:'energy'}] } },

/* --- control / utility attacks --- */
/* a beam, not a gun: it may take hold of anything it can see, friendly hull included */
'Tract Beam':             { activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'attack',range:'sensors',from:'offenseModule',
                                                attacks:1,dmg:0,check:'Cyber',targets:'any',
                                                onSuccess:[{op:'moveObject',what:'target',n:2}]}] } },
'Unwinder Array':         { onPlay:[{op:'addCharge',target:'self',n:4},{op:'exhaustSelf'}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'attack',range:'sensors',from:'any',attacks:1,dmg:0,
                                                check:'Cyber',
                                                onSuccess:[{op:'applyStatus',status:'noMove',
                                                            duration:'startOfYourNextTurn',target:'target'}]}] } },

/* --- movement --- */
'Grav Jet':               { activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'gainMove',from:'stat',stat:'speed'}] } },
'Rotating Jet':           { activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'moveObject',what:'ownModule',n:'any',
                                                placement:'adjacentToOwnModule'}] } },
'Recycle Jet':            { activate:{ cost:[{op:'exhaustSelf'},
                                             {op:'spendToken',token:'heatOrCharge',n:1,from:'anyOwnCard'}],
                                       effect:[{op:'moveObject',what:'ownModule',n:4}] } },
'After Burner':           { passive:[{ trigger:'onMove', optional:true,
                                       effect:[{op:'spendHeat',n:1,target:'self'},{op:'gainMove',n:1}] }],
                            activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'addHeat',target:'choose',n:1,filter:'takesHeat'}] } },
'Cosmic Shepherd':        { passive:[{ trigger:'onMove', optional:true,
                                       effect:[{op:'moveAsteroids',adjacentTo:'ownModules',n:'sameAsMove'}] }] },
'AI Piloting':            { passive:[{ trigger:'static',
                                       effect:[{op:'allowMoveOntoAsteroid'},
                                               {op:'destroyIfEndTurnOnAsteroid'}] }] },

/* --- defence / reaction --- */
'Reactive Armor':         { passive:[{ trigger:'onDamaged', optional:true,
                                       effect:[{op:'negateDamage'},{op:'trashSelf'}] }] },
'Chaff Clouds':           { passive:[{ trigger:'onTargeted', by:'enemyDeployable',
                                       checkOrSave:true,
                                       effect:[{op:'negateEffect'},{op:'trashSelf'}] }] },
'Phantom':                { passive:[{ trigger:'onTargeted', within:'sensors', optional:true,
                                       effect:[{op:'exhaustSelf'},
                                               {op:'skillCheck',skill:'Piloting',
                                                onSuccess:[{op:'gainMove',n:1},
                                                           {op:'mayNegateIfTargetMoved'}]}] }] },
'Shield Generator':       { activate:{ mode:'choice', options:[
                              { label:'Charge', cost:[{op:'exhaustSelf'}],
                                effect:[{op:'addCharge',target:'self',n:1}] },
                              { label:'Shield', cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                effect:[{op:'gainShield',n:2}] } ] } },
'Hardening Array':        { onPlay:[{op:'addCharge',target:'self',n:'2xEngineering'}],
                            activate:{ cost:[{op:'exhaustSelf'},{op:'spendCharge',n:1}],
                                       effect:[{op:'gainHull',n:1,mayExceed:true,
                                                target:'choose',filter:'moduleWithinSensors'}] } },

/* --- deck manipulation --- */
'Boost':                  { onPlay:[{op:'grantPlays',n:2},{op:'discardSelf'}] },
'Dynamo':                 { onPlay:[{op:'draw',n:2},{op:'grantPlays',n:1},{op:'discardSelf'}] },
'Heat Stores':            { onPlay:[{op:'addHeat',target:'allOwnCards',filter:'takesHeat',n:1},
                                    {op:'discardSelf'}] },
'Heat Sinks':             { passive:[
                              { trigger:'onFailCheck', optional:true,
                                effect:[{op:'spendHeat',n:2,target:'self'},{op:'reroll',n:1}] },
                              { trigger:'onExhaustMovementModule',
                                effect:[{op:'addHeat',target:'choose',n:1,filter:'takesHeat'}] }] },
'Revitaliser':            { onPlay:[{op:'addCharge',target:'self',n:6}],
                            passive:[{ trigger:'onWouldTrash', optional:true,
                                       effect:[{op:'spendCharge',n:3,target:'self'},
                                               {op:'convertTrashToDiscard'}] }] },
'Vital Burst':            { onPlay:[{op:'chooseCard',filter:'ownCardInPlayWithActivate',as:'t'},
                                    {op:'activateCard',ref:'t',times:2,payCosts:true},
                                    {op:'trashCard',ref:'t',keepFixedDurations:true},
                                    {op:'discardSelf'}] },

/* --- buffs / board --- */
'Overcharge':             { activate:{ cost:[{op:'exhaustSelf'},
                                             {op:'exhaustOther',filter:'movementModule',n:1}],
                                       effect:[{op:'buff',scope:'modules',filter:'cannonOrPD',
                                                dmg:1,range:2,
                                                duration:'startOfYourNextTurn'}] } },
'Full Volley':            { activate:{ cost:[],
                                       effect:[{op:'refresh',filter:'exhaustedOffenseModule',n:'all'},
                                               {op:'trashSelf'}] } },
'Divert Power':           { onPlay:[{op:'addToken',token:'Power',target:'choose',filter:'ownModule'}],
                            passive:[{ trigger:'static',
                                       effect:[{op:'buff',scope:'modules',filter:'hasPowerToken',
                                                hull:1,move:1,range:1,dmg:1}] }] },
'Decomp Strikes':         { passive:[{ trigger:'onAttackRoll', optional:true,
                                       condition:'attackerAdjacentToTerrain',
                                       effect:[{op:'reroll',n:1,scope:'missedAttacks'}] }] },
'Asteroid Builder':       { activate:{ mode:'choice', options:[
                              { label:'Charge', cost:[{op:'exhaustSelf'}],
                                effect:[{op:'addCharge',target:'self',n:2}] },
                              { label:'Build', cost:[{op:'exhaustSelf'},{op:'spendCharge',n:2}],
                                effect:[{op:'createAsteroid',n:1,at:'choose'}] } ] } },
'Debris Field':           { onPlay:[{op:'createAsteroid',n:1,at:'choose',within:'sensors',
                                     pattern:'selfAndAllAdjacent'},
                                    {op:'trashSelf'}] },
'SU Scanners':            { activate:{ cost:[{op:'exhaustSelf'}],
                                       effect:[{op:'revealStealth',within:'sensors'}] } }
},

/* =========================== MODULES =========================== */
mod: {

'Core':               { placement:'start', core:true,
                        passive:[{ trigger:'static', effect:[{op:'shareHullWithCoreModules'}] }] },
'Citadel':            { placement:'adjacentToCore',
                        passive:[{ trigger:'static',
                                   effect:[{op:'shareHullWithCore'},{op:'countsAsCore'}] }] },
'Armor':              { placement:'adjacentToAny' },
'Cannon':             { placement:'adjacentToCore',
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'attack',range:6,from:'self',attacks:2,dmg:2,
                                            dmgType:'kinetic'}] } },
'P.D.':               { placement:'adjacentToCore',
                        passive:[{ trigger:'onDeployableTargetsNearby', range:1, optional:true,
                                   effect:[{op:'activateTargetingDeployable',free:true}] }],
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'attack',range:2,from:'self',attacks:3,dmg:2,
                                            dmgType:'kinetic'}] } },
'Directed Laser Beam':{ placement:'adjacentToCore',
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'attack',range:'any',from:'self',attacks:1,dmg:2,
                                            dmgType:'energy',dmgIfRangeAtLeast:{range:10,dmg:4}}] } },
'Quantum Disrupter':  { placement:'adjacentToCore',
                        activate:{ cost:[{op:'exhaustOther',filter:'offenseModule',n:3}],
                                   effect:[{op:'attack',range:12,from:'self',attacks:1,dmg:6,
                                            check:'Sensors',dmgType:'bio'},
                                           {op:'createAnomaly',at:'random',fromSelf:true,minR:0,maxR:11}] } },
'SPEAR Connector':    { placement:'adjacentToAny',
                        activate:{ cost:[{op:'exhaustOther',filter:'offenseModuleAdjacent',n:2}],
                                   effect:[{op:'attack',range:'sensors',from:'self',attacks:4,dmg:2,
                                            dmgType:'energy',
                                            onHit:[{op:'applyStatus',status:'exhausted',
                                                    duration:'oneRound',target:'hitModule'}]}] } },
'Shield Connector':   { placement:'adjacentToAny',
                        activate:{ cost:[{op:'exhaustOther',filter:'adjacentModule',n:2}],
                                   effect:[{op:'gainShield',n:2}] } },
'Repulsor Unit':      { placement:'adjacentToAny',
                        activate:{ mode:'choice', options:[
                          { label:'Charge', cost:[{op:'exhaustSelf'}],
                            effect:[{op:'addCharge',target:'self',n:2}] },
                          { label:'Shield ally', cost:[{op:'exhaustSelf'},{op:'spendCharge',n:2}],
                            effect:[{op:'gainShield',n:4,target:'choose',
                                     filter:'alliedShipWithinSensors'}] } ] } },
'Comms Unit':         { placement:'adjacentToAny',
                        passive:[{ trigger:'static',
                                   effect:[{op:'buff',scope:'allies',within:'sensors',
                                            checks:2,saves:2}] }] },
'Decoy Module':       { placement:'adjacentToAny',
                        passive:[{ trigger:'static', effect:[{op:'stealthMimic',as:'module'}] }] },
'Graviton Engine':    { placement:'adjacentToAny', movement:true,
                        activate:{ cost:[{op:'exhaustOther',filter:'gravitonModule',n:'all',includeSelf:true}],
                                   effect:[{op:'gainMove',n:3}] } },
'Thrust Engine':      { placement:'adjacentToAny', movement:true,
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'gainMove',n:2}] } },

/* --- deployables --- */
'Ion Torpedo':        { deployable:true, speed:12,
                        onPlay:[{op:'exhaustSelf'}],
                        activate:{ cost:[],
                                   effect:[{op:'moveSelf',n:12,optional:true},
                                           {op:'attack',range:1,from:'self',attacks:1,dmg:3,
                                            check:'Sensors',dmgType:'kinetic'},
                                           {op:'removeSelf'}] } },
'TAT Guided':         { deployable:true, speed:4,
                        onPlay:[{op:'exhaustSelf'}],
                        activate:{ cost:[],
                                   effect:[{op:'moveSelf',n:4,optional:true},
                                           {op:'attack',range:1,from:'self',attacks:1,dmg:4,
                                            check:'Sensors',dmgType:'kinetic',
                                            onHit:[{op:'removeSelf'}]}] } },
'Fusion Mine':        { deployable:true, speed:0,
                        passive:[{ trigger:'onDestroyedOrEnemyEnters',
                                   effect:[{op:'activateSelf'}] }],
                        activate:{ cost:[],
                                   effect:[{op:'attack',range:1,from:'self',aoe:'radius',
                                            attacks:1,dmg:'2d6',save:'Piloting',dmgType:'kinetic'},
                                           {op:'removeSelf'}] } },
'Decoy Deployable':   { deployable:true, speed:0,
                        passive:[{ trigger:'static', effect:[{op:'stealthMimic',as:'deployable'}] }] },
'Shuttle Craft I':    { deployable:true, speed:2,
                        onPlay:[{op:'addCharge',target:'self',n:1,actsAsShield:true}],
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'moveSelf',n:2},
                                           {op:'chooseOne', options:[
                                             { label:'Attack', effect:[{op:'attack',range:1,from:'self',
                                                                        attacks:1,dmg:1}] },
                                             { label:'Scan', effect:[{op:'skillCheck',skill:'Sensors',
                                                                      onSuccess:[{op:'scan'}]}] } ]}] } },
'Tug Craft I':        { deployable:true, speed:2,
                        onPlay:[{op:'addCharge',target:'self',n:1,actsAsShield:true}],
                        activate:{ cost:[{op:'exhaustSelf'}],
                                   effect:[{op:'moveSelf',n:2},
                                           {op:'chooseOne', options:[
                                             { label:'Attack', effect:[{op:'attack',range:1,from:'self',
                                                                        attacks:1,dmg:1}] },
                                             { label:'Shove', effect:[{op:'attack',range:1,from:'self',
                                                                       attacks:1,dmg:0,save:'Piloting',
                                                                       onHit:[{op:'moveObject',what:'target',n:1}]}] } ]}] } }
}
};
