var MOD_PRESETS = [
    {name:'Armor', req:'Adjacent to any, 2 spaces from Core', hull:'2', type:'module', tt:'defense', onbuild:'', passive:'', onactivate:'', onactivateenergy:''},
    {name:'Cannon', req:'Adjacent to Core', hull:'1', type:'module', tt:'offense', onbuild:'', passive:'', onactivate:'Exhaust to Target an object:\nRange: 6 from self, Attacks: 2, Dmg: 2 💥', onactivateenergy:'2'},
    {name:'Comms Unit', req:'Adjacent to any', hull:'2', type:'module', tt:'science', onbuild:'', passive:'Allies within Sensor range of this gain a +2 bonus on all Checks and Saves.', onactivate:'', onactivateenergy:''},
    {name:'Graviton Engine', req:'Adjacent to any', hull:'1', type:'module', tt:'movement', onbuild:'', passive:'Gain 1 Speed per non Engine module on your ship (if you later gain/lose modules adjust Speed).', onactivate:'', onactivateenergy:''},
    {name:'Ion Torpedo', req:'', hull:'1', duration:'1', speed:'12', type:'deployable', tt:'offense', onbuild:'Exhaust', passive:'', onactivate:'You may move this deployable up to 12 spaces, then Target an object:\nRange: 1 from self, Check: Sensors, Dmg: 3💥\n\nAfter activating remove this deployable.', onactivateenergy:''},
    {name:'P.D.', req:'Adjacent to core', hull:'1', type:'module', tt:'offense', onbuild:'', passive:'If a Deployable Targets any Module within Range 1 from self, you may immediately use the Active ability on that deployable for free.', onactivate:'Exhaust to Target an object:\nRange: 2 from self, Attacks: 3, Dmg: 2 💥', onactivateenergy:'2'},
    {name:'Repulsor Unit', req:'Adjacent to any', hull:'4', charges:'0', type:'module', tt:'defense', onbuild:'', passive:'', onactivate:'Exhaust to add 2 charges to this OR remove 2 charges and give 4 shield to an allied ship within Sensor range from this.', onactivateenergy:'2'},
    {name:'Shuttle Craft I', req:'', hull:'1', speed:'2', charges:'1', type:'deployable', tt:'science', onbuild:'This gains 1 charge. This charge acts as a shield.', passive:'', onactivate:'Exhaust to Move 2, and choose one of the following:\n- Target an Object: Range: 1, Attacks: 1, Dmg: 1; OR\n- Make a Sensor Check to Scan', onactivateenergy:''},
    {name:'Tug Craft I', req:'', hull:'1', speed:'2', charges:'1', type:'deployable', tt:'movement', onbuild:'This gains 1 charge. This charge acts as a shield.', passive:'', onactivate:'Exhaust to Move 2, choose one of the following:\n- Target an Object: Range: 1, Attacks: 1, Dmg: 1; OR\n- Target an Object: Range: 1, Save: Piloting (On hit Move the object 1 space)', onactivateenergy:''}
  ];
MOD_PRESETS.sort(function(a,b){return a.name.toLowerCase().localeCompare(b.name.toLowerCase());});
